### ISSUE TITLE
Initializer has some sort of conflict with delegation in Rails 4.2.10

### ISSUE THREAD

**Issue by joelvh** [eventide-project/initializer#3]
Just added `eventide-postgres` to our Gemfile and booted up the Rails app without any other changes. It looks like `Visibility.lazy` is conflicting with Ruby's `enumerable.lazy` helper method. Ruby's `lazy` doesn't take any arguments, but `Visibility.lazy` does.

Thoughts?

```
wrong number of arguments (given 0, expected 1)

evt-initializer (0.1.0.2) lib/initializer/visibility.rb:22:in `lazy'
activerecord (4.2.10) lib/active_record/relation/delegation.rb:70:in `block in lazy'
activerecord (4.2.10) lib/active_record/associations/collection_proxy.rb:874:in `block in scoping'
activerecord (4.2.10) lib/active_record/relation.rb:302:in `scoping'
activerecord (4.2.10) lib/active_record/associations/collection_proxy.rb:874:in `scoping'
activerecord (4.2.10) lib/active_record/relation/delegation.rb:70:in `lazy'
```

**Comment by sbellware** [comment]
@joelvh 

There are parts of Eventide that _can_ work within Rails and work well within Rails, but the whole toolkit is intended to be run in services that are entirely separate from Rails.

Architecturally, Rails is a _front end_ toolkit. Eventide is a _back end_ toolkit. Eventide isn't intended to be run in the same process as Rails, and thus you're seeing the conflicts and incompatibilities.

The parts of Eventide that _do_ make sense to run within a Rails app are the libraries that support event sourcing (entity projection, entity store, entity cache, and the like).

@ntl Might have something to add to this thread before we make a decision as to how to disposition this issue.

**Comment by ntl** [comment]
@joelvh can you paste the line of code that is leading to this error?

**Comment by sbellware** [comment]
@ntl My understanding is that @joelvh encountered this issue by merely _loading_ Eventide

**Comment by ntl** [comment]
@sbellware @joelvh 

If that's the case, then rails will need to be started with the backtrace filter turned completely off. When I start rails on my laptop, the class method `.lazy` never gets invoked on either `ActiveRecord::Base` (the class) or any of its subclasses. Thus, I can't really reproduce this issue at the moment, so I'll have to use the full stack trace in order to figure out how.

**Comment by joelvh** [comment]
@ntl I have been reading through the Eventide code and looking through dependencies. At the point where `entity_cache` calls `Initializer.activate`, `Object` is extended with `Initializer::Macro` by default. That macro has some mixins with the `lazy` method on it.

The conflict in Rails is in this gem: https://github.com/allenwq/devise-multi_email/blob/master/lib/devise/multi_email/parent_model_manager.rb#L65

I did a quick test and loaded up IRB -- and it seems that `[].lazy` does not cause the error. However, `Initializer.activate` adds the class method `Array.lazy` and it gives this error.

I realize that finding is odd because it should not cause a problem because `Array.lazy` should never be called on the class. But, unless there's a bug in the linked gem, something is causing a conflict that wasn't there before.

Let me know if this helps track things down - I will try to give the full stack trace if needed, when I can.

**Comment by ntl** [comment]
I've found the root cause of the problem. I'll explain it in terms of an example:

```ruby
class Parent < ActiveRecord::Base
  has_many :children
end

class Child < ActiveRecord::Base
  def self.some_method
    # ...
  end
end

parent = Parent.create!

children_association = parent.children
```

For the remainder of this explanation, I'm going to refer to `child_association` as the "association proxy." Essentially, it's a proxy object that allows a few types of methods to get called on it:

1. Array methods, e.g. `#first`, `#last`, `#map`, `#select`, or even `#to_a`
2. ActiveRecord query builder methods, e.g. `.order('created_at DESC')` on `.where('created_at > NOW()')`
3. Methods on the Child _class_ (not instance), e.g. `Child.some_method` in the above snippet. These class methods are treated just like scopes

When the association proxy attempts to dispatch a method, it _first_ checks to see if the associated class responds to the method _before_ it determines if the method should be treated as an Array method like `#map`. So, we know that `children_association.some_method` will ultimately cause `Child.some_method` to get caused. In a rails project _without_ eventide, `.lazy` is not a class method on ActiveRecord::Base subclasses, and association proxies delegate it without any trouble. Once eventide gets loaded, however, `.lazy` _is_ on Class, and thus on ActiveRecord::Base, and thus on all ActiveRecord subclasses. At that point, association proxies will dispatch `.lazy` to the one defined by the initializer library.

**Conclusion**

In the context of `Enumerable` objects in ruby, `.lazy` has a precise meaning, and Rails is justified in implementing an enumerable `.lazy` on any object it defines that is meant to be used in place of an Array (or an Enumerable). In the context of this library, which is meant to provide conveniences for defining classes, `.lazy` has an entirely different meaning. This is all absolutely fine -- the meaning of any particular method on any object is largely dependent upon the context of its class. However, association proxies in rails have a problem -- they happily accept methods intended for the associated class, _and_ they accept enumerable methods. Thus multiple contexts are comingling, and there's a conflict.

**Solution**

Rails internal classes typically wear so many different hats (i.e. define so many methods on them) that I don't think we should entertain the notion of prohibiting conflicts like this unless there is no other choice. In the meantime, @joelvh, I'd like you to try adding these two lines of code to Rails' bootup process (i.e. an initializer, or `config/boot.rb`):

```ruby
require 'initializer'; Initializer.activate

ActiveRecord::Base.singleton_class.__send__(:undef_method, :lazy)
```

This will activate the `initializer` gem's extensions to the `Object` class, and _then_ remove `.lazy` from ActiveRecord::Base (and thus its subclasses). I believe this should fix the present issue. Of course, it's reasonable to then ask, "how many more conflicts are there between rails and eventide?" I don't have a great answer there, but this is the first reported conflict, and calling `.lazy` on an ActiveRecord association seems somewhat esoteric.

@sbellware could you weigh in on this?

**Comment by sbellware** [comment]
It's impossible to account for the things that are done in Rails. Things like Eventide largely exist so that we don't have to volunteer for more entanglements with Rails.

That said, writing a command message from a Rails controller is a valid use case. And even though it's a secondary use case, projecting events into an entity within a Rails app is a legitimate use case.

But there's only so much that we can do in accounting for some of the more occult design decisions that the Rails project has made.

We can change `.lazy` to `.deferred`, and that will be fine until Rails adds a `.deferred` to their colossal API. But we'd be inviting ourselves to an endless game of whack-a-mole with subsequent Rails incompatibilities that are due to things that I would be hard pressed to not refer to as "mistakes".

So, I think that the spot solution that you've provided in that initializer is "good enough", all things considered. If there are more of these things that we find, maybe we'll create a compatibility library that un-defines yet more Rails mechanisms.

**Comment by sbellware** [comment]
We've been talking about the implications of this throughout this afternoon. No firm answers yet, but some potential solutions that we're optimistic about.

**Comment by joelvh** [comment]
@ntl your conclusion makes sense now that I think about it - that Rails uses class methods as scopes. In this specific case, I'll also look at the gem calling `lazy` to see why it's called on an Active Record relation rather than an instance of an Array.

@sbellware regarding your note about the fact that some Eventide code will end up in Rails, that is one of the things that I was left with figuring out last night when we discussed Rails as a "front end" on Slack. How they live together in that regard, seems like a topic to solve for. If it's not Rails, but rather some other front-end that provides an API or other interface to the outside world, is a use case that I'll be exploring with you guys as well. However, not sure this is the right place to continue that conversation.

Thanks for tracking this down. Look forward to seeing where the broader conversation goes.

**Comment by joelvh** [comment]
@ntl adding `ActiveRecord::Base.singleton_class.__send__(:undef_method, :lazy)` to an initializer worked.

I wonder if there's a way to specify a folder in which to load up all classes and call `Initializer.activate` on those?

I'm going to create a PR to the gem calling `lazy` to address the unneeded reference.

**Comment by ntl** [comment]
I don't think that would be possible -- you'd have to pass in already initialized constants to `Initializer.activate`, but those constants couldn't load without initializer activated. I think Scott and I are going to be able to address this (and all other potential monkeypatching conflicts) soon. I'm glad there's a workaround for the (hopefully temporary) time being.

**Comment by sbellware** [comment]
@joelvh I can't expect that PR will receive a warm reception. There's no reason for a well-adopted project to make a modification out of deference for a project that is as-yet under the radar.

If you do submit that PR, it would be great if we're not mentioned as the motivator.
